title: "Mozilla.cz - prezentace"
language: "cs"

permalink: pretty

# Build settings
markdown: kramdown
include: [
    '/_pages',
    '_common',
]
exclude:
  - vendor
  - Makefile
  - README.md
  - CODE_OF_CONDUCT.md
  - scripts
