on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch: # allows to be run manually

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Cache installed Ruby dependencies
        uses: actions/cache@v2
        env:
          cache-name: vendor-bundle
        with:
          path: vendor/.bundle
          key: ${{ runner.os }}_build_${{ env.cache-name }}_${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}_build_${{ env.cache-name }}_
      - name: Build site
        run: make build_in_docker
      - name: Save built site for deploy
        uses: actions/upload-artifact@v2
        with:
          name: _site
          path: _site
          retention-days: 7
  deploy:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/master'
    needs: build
    steps:
      - name: Download built site for deploy
        uses: actions/download-artifact@v2
        with:
          name: _site
          path: _site
      - name: Avoid further processing by Jekyll in Github Pages
        run: touch _site/.nojekyll
      - name: Deploy to GitHub Page
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _site
          CLEAN: true
          SINGLE_COMMIT: true
