name: Build

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch: # allows to be run manually
  workflow_call: # when called from another workflow

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Cache installed Gems for the project
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Build site
        run: make all_in_container
      - name: Save built site for deploy
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site
          retention-days: 7
